input_data_path: 'data/raw/heart_cleveland_upload.csv'
output_model_path: 'models/model.pkl'
metric_path: 'models/metrics.json'
splitting_params:
  val_size: 0.2
  random_state: 0
  stratify: 'yes'
training_params:
  model_type: 'LogisticRegression'
  model_params:
    max_iter: 1000
feature_params:
  categorical_features:
    - 'sex'
    - 'cp'
    - 'fbs'
    - 'restecg'
    - 'exang'
    - 'slope'
    - 'ca'
    - 'thal'
  numerical_features:
    - 'age'
    - 'trestbps'
    - 'chol'
    - 'oldpeak'
    - 'thalach'
  features_to_drop: 
  target_col: 'condition'